Use directly FromStr types in StructOpt
With wrong values instead of getting:
[2021-09-21T13:25:13Z ERROR bdk_cli] Bip32(Base58(BadChecksum(1292914229, 1275556062)))

you get:
error: Invalid value for '--xprv <XPRV>': base58 encoding error: base58ck checksum 0x4c0770de does not match expected 0x4d104e35